### ISSUE TITLE
docker default bridge0 instructions

### ISSUE THREAD

**Issue by hamhpc** [Islandora-Collaboration-Group/ISLE#100]
I ran into an issue where within our organizations private network that the default docker bridge network was using the same address space. So connections to the docker host weren't working properly since it thought the same network was within docker. I'm looking at https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/ to figure out how to change the default bridge network and can update with more info when I work out those steps. I just figured it would be good to make note of this somewhere. In case someone else runs into this.

**Comment by br2490** [comment]
@hamhpc there are two ways to define a docker network, i'd like to show you the compose way as it is efficient and reproducible if you move hosts:

For each service in the stack a `network:` a section must be added to tell that container to sit on your defined network.

With each service having that definition we create a "top-level" service network configuration (typically) found at the end of the docker-compose.yml.

Here is a stubbed example, please also [check this docker-compose](https://github.com/BarnardArchives/barnard_isle_docker/blob/master/docker-compose.yml) for an isle-specific example!  Happy to help
```
services:
  apache:
      image: ...
      ...(other container settings)...
     networks:
        <name of the network:EXAMPLE>

networks:
    <name of the network:EXAMPLE>:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.100.1/24
                gateway: 192.168.1.1
```
